apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  name: citrixdemo
  namespace: default
spec:
  commonName: kuard.citrixdemo.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: citrixdemo
  duration: 60m
  renewBefore: 58m
  usages:
  - digital signature
  - key encipherment
