apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/kube-ingress
    server: <Vault_URL>
    auth:
      appRole:
        path: approle
        roleId: <role_id>
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
